In [11]:
import pandas as pd
import numpy as np

import requests
import os
import pandas as pd
import numpy as np
import nltk

## AFFECT DIMENSIONS

In [12]:
AIL_df = pd.read_csv("../LEXIKA/fixed_csvs/fixed_greek_NRC_AIL_lex_2023_01.csv")
#or pd.read_csv("../LEXIKA/fixed_csvs/edited_nrc_AIL_lex.csv")

In [13]:
AIL_df

,English,Greek,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,True,αληθής,0.0,0.00,0.0,0.000,0.328,0.000,0.0,0.789
1,aaaaaaah,ααααααχ,0.0,0.00,0.0,0.344,0.000,0.000,0.0,0.000
2,aaaah,ααααχ,0.0,0.00,0.0,0.234,0.000,0.000,0.0,0.000
3,abacus,άβακας,0.0,0.00,0.0,0.000,0.000,0.000,0.0,0.406
4,abandon,εγκαταλείπω,0.0,0.00,0.0,0.531,0.000,0.703,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...
8869,zen,ζεν,0.0,0.00,0.0,0.000,0.515,0.000,0.0,0.000
8870,zest,πάθος,0.0,0.57,0.0,0.000,0.516,0.000,0.0,0.289
8871,zest,ζέση,0.0,0.57,0.0,0.000,0.516,0.000,0.0,0.289
8872,zest,ενθουσιασμός,0.0,0.57,0.0,0.000,0.516,0.000,0.0,0.289
8873,zest,όρεξη,0.0,0.57,0.0,0.000,0.516,0.000,0.0,0.289

In [16]:
AIL_df.drop('English', axis=1, inplace=True)

In [17]:
AIL_df.columns

Index(['Greek', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust'],
      dtype='object')

In [18]:
df1 = AIL_df.set_index('Greek').stack().droplevel(0).reset_index(name='AffectDimension')

In [19]:
df1

              index  AffectDimension
0             anger            0.000
1      anticipation            0.000
2           disgust            0.000
3              fear            0.000
4               joy            0.328
...             ...              ...
70987          fear            0.000
70988           joy            0.516
70989       sadness            0.000
70990      surprise            0.000
70991         trust            0.289

[70992 rows x 2 columns]

In [20]:
df2 = AIL_df.set_index('Greek').stack().droplevel(1).reset_index(name='AffectDimension')

In [21]:
df2

        Greek  AffectDimension
0      αληθής            0.000
1      αληθής            0.000
2      αληθής            0.000
3      αληθής            0.000
4      αληθής            0.328
...       ...              ...
70987   όρεξη            0.000
70988   όρεξη            0.516
70989   όρεξη            0.000
70990   όρεξη            0.000
70991   όρεξη            0.289

[70992 rows x 2 columns]

In [22]:
AIL_df = pd.merge(df2, df1, left_index=True, right_index=True)
AIL_df

        Greek  AffectDimension_x         index  AffectDimension_y
0      αληθής              0.000         anger              0.000
1      αληθής              0.000  anticipation              0.000
2      αληθής              0.000       disgust              0.000
3      αληθής              0.000          fear              0.000
4      αληθής              0.328           joy              0.328
...       ...                ...           ...                ...
70987   όρεξη              0.000          fear              0.000
70988   όρεξη              0.516           joy              0.516
70989   όρεξη              0.000       sadness              0.000
70990   όρεξη              0.000      surprise              0.000
70991   όρεξη              0.289         trust              0.289

[70992 rows x 4 columns]

In [23]:
AIL_df

        Greek  AffectDimension_x         index  AffectDimension_y
0      αληθής              0.000         anger              0.000
1      αληθής              0.000  anticipation              0.000
2      αληθής              0.000       disgust              0.000
3      αληθής              0.000          fear              0.000
4      αληθής              0.328           joy              0.328
...       ...                ...           ...                ...
70987   όρεξη              0.000          fear              0.000
70988   όρεξη              0.516           joy              0.516
70989   όρεξη              0.000       sadness              0.000
70990   όρεξη              0.000      surprise              0.000
70991   όρεξη              0.289         trust              0.289

[70992 rows x 4 columns]

In [24]:
AIL_df.drop('AffectDimension_y', axis=1, inplace=True)

In [25]:
AIL_df.rename(columns={'Greek': 'term', 'AffectDimension_x': 'score', 'index': 'AffectDimension'}, inplace=True)

In [26]:
AIL_df

         term  score AffectDimension
0      αληθής  0.000           anger
1      αληθής  0.000    anticipation
2      αληθής  0.000         disgust
3      αληθής  0.000            fear
4      αληθής  0.328             joy
...       ...    ...             ...
70987   όρεξη  0.000            fear
70988   όρεξη  0.516             joy
70989   όρεξη  0.000         sadness
70990   όρεξη  0.000        surprise
70991   όρεξη  0.289           trust

[70992 rows x 3 columns]

In [27]:
AIL_df = AIL_df[AIL_df.score != 0]

In [28]:
AIL_df.reset_index(drop=True, inplace = True)
AIL_df

               term  score AffectDimension
0            αληθής  0.328             joy
1            αληθής  0.789           trust
2           ααααααχ  0.344            fear
3             ααααχ  0.234            fear
4            άβακας  0.406           trust
...             ...    ...             ...
15652  ενθουσιασμός  0.516             joy
15653  ενθουσιασμός  0.289           trust
15654         όρεξη  0.570    anticipation
15655         όρεξη  0.516             joy
15656         όρεξη  0.289           trust

[15657 rows x 3 columns]

In [29]:
AIL_df[AIL_df.term=='πάθος']

        term  score AffectDimension
9392   πάθος  0.633    anticipation
9393   πάθος  0.603             joy
9394   πάθος  0.469           trust
15645  πάθος  0.570    anticipation
15646  πάθος  0.516             joy
15647  πάθος  0.289           trust

In [30]:
AIL_df[AIL_df.term=='απαίσιος']

           term  score AffectDimension
48     απαίσιος  0.664         disgust
49     απαίσιος  0.738            fear
960    απαίσιος  0.409           anger
961    απαίσιος  0.562         disgust
962    απαίσιος  0.672            fear
963    απαίσιος  0.641         sadness
4915   απαίσιος  0.545           anger
4916   απαίσιος  0.734         disgust
4917   απαίσιος  0.250            fear
5935   απαίσιος  0.742           anger
5936   απαίσιος  0.656         disgust
5937   απαίσιος  0.734            fear
12227  απαίσιος  0.781           anger
12228  απαίσιος  0.750         disgust
12229  απαίσιος  0.672            fear
12942  απαίσιος  0.742         disgust
13567  απαίσιος  0.688           anger
13568  απαίσιος  0.562         disgust
13569  απαίσιος  0.594            fear
13570  απαίσιος  0.578         sadness
14895  απαίσιος  0.797           anger
14896  απαίσιος  0.641         disgust
14897  απαίσιος  0.594            fear

In [31]:
AIL_df = AIL_df.drop_duplicates(['term','AffectDimension'], keep='last')

In [32]:
AIL_df[AIL_df.term=='απαίσιος']

           term  score AffectDimension
13570  απαίσιος  0.578         sadness
14895  απαίσιος  0.797           anger
14896  απαίσιος  0.641         disgust
14897  απαίσιος  0.594            fear

In [33]:
AIL_df.AffectDimension.value_counts()

fear            2167
anger           1939
trust           1776
sadness         1718
joy             1533
disgust         1497
anticipation    1127
surprise         859
Name: AffectDimension, dtype: int64

In [34]:
import nltk.sentiment
w2affect = []
for w,score,dim in AIL_df.values:
    w2affect.append({dim:score,'w':w})
w2affects = {}
df = pd.DataFrame(w2affect)
df = df.groupby('w').sum().reset_index()
for w,anger,fear,joy,sadness, trust, disgust, anticipation, surprise in df[['w','anger','fear','joy','sadness', 'trust', 'disgust', 'anticipation', 'surprise']].values:
    w2affects[w] = {'anger':anger,'joy':joy,'sadness':sadness,'fear':fear,'trust': trust, 'disgust':disgust, 'anticipation':anticipation,'surprise': surprise }

def get_affect_intensity_score(doc,tokenizer=nltk.word_tokenize,agg='mean'):
    if type(doc)==str:
        doc = tokenizer(doc)
    assert type(doc)==list,"please input either a list or a string"
    matches = []
    for w in doc:
        w = w.lower()
        if w in w2affects:
            matches.append(w2affects[w])
    if len(matches)==0:
        return {'anger':np.nan,'joy':np.nan,'sadness':np.nan,'fear':np.nan,'trust':np.nan,'disgust':np.nan,'anticipation':np.nan,'surprise':np.nan}
    scores = pd.DataFrame(matches)
    if agg=='mean':
        scores = scores.mean()
    elif agg=='max':
        scores =  scores.max()
    else:
        scores = agg(scores)
    return dict(scores)

get_affect_intensity_score('Υπάρχει πολύ μίσος και αηδία στην ατμόσφαιρα. Είσαι απαίσιος!')

{'anger': 0.8410000000000001,
 'joy': 0.0,
 'sadness': 0.5833333333333334,
 'fear': 0.6043333333333333,
 'trust': 0.0,
 'disgust': 0.6956666666666668,
 'anticipation': 0.0,
 'surprise': 0.0}

In [35]:
# only anger 

w2affect = []
for w,score,dim in AIL_df.values:
    w2affect.append({dim:score,'w':w})
w2affects = {}
df = pd.DataFrame(w2affect)
df = df.groupby('w').sum().reset_index()
for w,anger,fear,joy,sadness in df[['w','anger','fear','joy','sadness']].values:
    w2affects[w] = {'anger':anger,'joy':joy,'sadness':sadness,'fear':fear}

def get_anger_score(doc,tokenizer=nltk.word_tokenize,agg='mean'):
    if type(doc)==str:
        doc = tokenizer(doc)
    assert type(doc)==list,"please input either a list or a string"
    matches = []
    for w in doc:
        w = w.lower()
        if w in w2affects:
            matches.append(w2affects[w])
    if len(matches)==0:
        return {'anger':np.nan,'joy':np.nan,'sadness':np.nan,'fear':np.nan}
    scores = pd.DataFrame(matches)
    if agg=='mean':
        scores = scores.mean()
    elif agg=='max':
        scores =  scores.max()
    else:
        scores = agg(scores)
    return list(dict(scores).values())[0]

get_anger_score('Είμαι πολύ θυμωμένος και έχω νεύρα και θυμό και δεν αντέχω!')

0.4056666666666667

In [73]:
#df_news ['Anger_intensity'] = df_news['lemmatized'].apply(lambda x: get_anger_score(x))

In [74]:
# only joy

w2affect = []
for w,score,dim in AIL_df.values:
    w2affect.append({dim:score,'w':w})
w2affects = {}
df = pd.DataFrame(w2affect)
df = df.groupby('w').sum().reset_index()
for w,anger,fear,joy,sadness in df[['w','anger','fear','joy','sadness']].values:
    w2affects[w] = {'anger':anger,'joy':joy,'sadness':sadness,'fear':fear}

def get_joy_score(doc,tokenizer=nltk.word_tokenize,agg='mean'):
    if type(doc)==str:
        doc = tokenizer(doc)
    assert type(doc)==list,"please input either a list or a string"
    matches = []
    for w in doc:
        w = w.lower()
        if w in w2affects:
            matches.append(w2affects[w])
    if len(matches)==0:
        return {'anger':np.nan,'joy':np.nan,'sadness':np.nan,'fear':np.nan}
    scores = pd.DataFrame(matches)
    if agg=='mean':
        scores = scores.mean()
    elif agg=='max':
        scores =  scores.max()
    else:
        scores = agg(scores)
    return list(dict(scores).values())[1]

get_joy_score('είναι ωραίος και χαίρομαι να τον βλέπω.')

0.4695

In [48]:
#df_news ['Joy_intensity'] = df_news['lemmatized'].apply(lambda x: get_joy_score(x))

In [75]:
# only sadness

w2affect = []
for w,score,dim in AIL_df.values:
    w2affect.append({dim:score,'w':w})
w2affects = {}
df = pd.DataFrame(w2affect)
df = df.groupby('w').sum().reset_index()
for w,anger,fear,joy,sadness in df[['w','anger','fear','joy','sadness']].values:
    w2affects[w] = {'anger':anger,'joy':joy,'sadness':sadness,'fear':fear}

def get_sadness_score(doc,tokenizer=nltk.word_tokenize,agg='mean'):
    if type(doc)==str:
        doc = tokenizer(doc)
    assert type(doc)==list,"please input either a list or a string"
    matches = []
    for w in doc:
        w = w.lower()
        if w in w2affects:
            matches.append(w2affects[w])
    if len(matches)==0:
        return {'anger':np.nan,'joy':np.nan,'sadness':np.nan,'fear':np.nan}
    scores = pd.DataFrame(matches)
    if agg=='mean':
        scores = scores.mean()
    elif agg=='max':
        scores =  scores.max()
    else:
        scores = agg(scores)
    return list(dict(scores).values())[2]

get_sadness_score('Δεν μπορεί να ζούμε αυτή την τραγωδία που έπληξε τη χώρα. ')

0.688

In [50]:
df_news ['Sadness_intensity'] = df_news['lemmatized'].apply(lambda x: get_sadness_score(x))

In [76]:
# only fear

w2affect = []
for w,score,dim in AIL_df.values:
    w2affect.append({dim:score,'w':w})
w2affects = {}
df = pd.DataFrame(w2affect)
df = df.groupby('w').sum().reset_index()
for w,anger,fear,joy,sadness in df[['w','anger','fear','joy','sadness']].values:
    w2affects[w] = {'anger':anger,'joy':joy,'sadness':sadness,'fear':fear}

def get_fear_score(doc,tokenizer=nltk.word_tokenize,agg='mean'):
    if type(doc)==str:
        doc = tokenizer(doc)
    assert type(doc)==list,"please input either a list or a string"
    matches = []
    for w in doc:
        w = w.lower()
        if w in w2affects:
            matches.append(w2affects[w])
    if len(matches)==0:
        return {'anger':np.nan,'joy':np.nan,'sadness':np.nan,'fear':np.nan}
    scores = pd.DataFrame(matches)
    if agg=='mean':
        scores = scores.mean()
    elif agg=='max':
        scores =  scores.max()
    else:
        scores = agg(scores)
    return list(dict(scores).values())[3]

get_fear_score('Είναι φοβερή η τραγωδία που έπληξε τη χώρα. ')

0.562

In [52]:
df_news ['Fear_intensity'] = df_news['lemmatized'].apply(lambda x: get_fear_score(x))

In [53]:
df_news [['Anger_intensity','Joy_intensity', 'Sadness_intensity','Fear_intensity']]

     Anger_intensity  Joy_intensity  Sadness_intensity  Fear_intensity
0           0.049520       0.129600           0.123360        0.138320
1           0.096336       0.289206           0.069523        0.107243
2           0.129667       0.213317           0.271070        0.258387
3           0.081609       0.107174           0.047565        0.133174
4           0.163806       0.120645           0.188903        0.270032
..               ...            ...                ...             ...
566         0.114684       0.092806           0.315796        0.302255
567         0.107920       0.120800           0.222160        0.235840
568         0.047246       0.147696           0.114493        0.195449
569         0.117222       0.125056           0.186111        0.193444
570         0.000000       0.254905           0.095762        0.088000

[571 rows x 4 columns]

In [54]:
cols = ['Anger_intensity', 'Joy_intensity', 'Sadness_intensity',
       'Fear_intensity']
df_news[cols] = df_news[cols].apply(pd.to_numeric, errors='coerce', axis=1)